- name: Installation Packet Apache
  apt: name=apache2 update_cache=yes state=latest
 
- name: Démarre apache2 Service
  systemd: name=apache2 state=started enabled=yes

#- name: Enable the Apache2 module wsgi
#  community.general.apache2_module:
#    name: 
#      - rewrite
#      - deflate
#      - headers
#      - ssl
#    state: present

- name: Active module apache2 rewrite
  ansible.builtin.command: a2enmod rewrite

- name: Active module apache2 deflate
  ansible.builtin.command: a2enmod deflate

- name: Active module apache2 headers
  ansible.builtin.command: a2enmod headers

- name: Active module apache2 ssl
  ansible.builtin.command: a2enmod ssl


- name: Démarre apache2 Service
  systemd: name=apache2 state=restarted enabled=yes
 
- name: Creation du Document Root Apache
  file:
    path: "/var/www/{{ http_host }}"
    state: directory
    owner: "www-data"
    group: "www-data"
    mode: '0755'

- name: Suppression fichier par defaut apache de virtual host
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
 
- name: Créer Apache VirtualHost
  template:
    src: "files/httpd.conf"
    dest: "/etc/apache2/sites-enabled/000-default.conf"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
