#PHP Confs
php_modules: [ 'php', 'php-curl', 'php-gd', 'php-mbstring', 'php-xml', 'php-xmlrpc', 'php-soap', 'php-intl', 'php-zip' ]
 
#MySQL Confs
mysql_root_password: "Password"
mysql_db: "wordpressdb"
mysql_user: "wordpressuser"
mysql_password: "Password"
mysql_host: "localhost"
 
#HTTP Confs
http_host: "wp.example.com"
http_conf: "wp.example.com.conf"
http_port: "80"
