# Configuration Mysql
    - name: Installation paquet MySQL "MariaDB"
      apt: name={{ item }} update_cache=yes state=latest
      loop: [ 'mariadb-server', 'php-mysqlnd', 'python3-pymysql' ]
 
    - name: Démarre Service Mariadb
      systemd: name=mariadb state=restarted enabled=yes
 
    - name: Créer le mot de passe ROOT 
      mysql_user:
        login_password: '{{ mysql_root_password }}'
        name: 'root'
        password: '{{ mysql_root_password }}'
        login_unix_socket: /var/run/mysqld/mysqld.sock
        state: present

    - name: Retire les comptes anonymes
      mysql_user:
        name: ''
        host_all: yes
        state: absent
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Retire la base MYSQL test
      mysql_db:
        name: test
        state: absent
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Créer la base de donnée WORDPRESS
      mysql_db:
        name: "{{ mysql_db }}"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"
 
    - name: Créer l'utilisateur pour la base de donnée WORDPRESS
      mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_password }}"
        priv: "{{ mysql_db }}.*:GRANT,ALL"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"
        host: "%"
